version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    env_file: 
      - .env
    depends_on:
      - db

  db:
    image: mysql:5.7.34
    env_file: 
      - .env