version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:5.7.34
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    env_file:
      - .env
