FROM golang:1.16-alpine

WORKDIR /app

COPY . ./

RUN apk add --update gcc musl-dev && \ 
    go mod download && \
    go build -o /$APP_NAME && \
    chmod +x ./scripts/init.sh

ENTRYPOINT [ "./scripts/init.sh" ]
