FROM golang:1.16-buster AS build

WORKDIR /app

COPY . ./

RUN apt-get update && \ 
    apt-get install gcc musl-dev && \ 
    go mod download && \
    go build -o /steam-crawler


FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /steam-crawler /steam-crawler

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/steam-crawler"]